site_name: NCHS Cybersecurity 

nav:
  - Home: index.md
  - About: about.md
theme:
  name: simple-blog
  favicon: img/logo.png
  logo: img/logo.png
  analytics:
    gtag: G-DRPQMPQQS6
    anonymize_ip: true
  highlightjs: true
  hljs_languages:
    - python
    - yaml
    - C
  color_mode: dark
  user_color_mode_toggle: true



