site_name: NCHS Cybersecurity 
site_url: https://mohamed-morsy33.github.io/cybersecuritynchs/

plugins:
  - search
  
nav:
  - Home: index.md
  - Unit 1:
    - Overview: unit1.md
    - Lesson 1.1: LECTURES/unit1/lesson1-1.md
    - Lesson 1.2: LECTURES/unit1/lesson1-2.md
    - Lesson 1.3: LECTURES/unit1/lesson1-3.md
    - Linux Installation Process: LECTURES/unit1/installation-process.md
  - Unit 2: unit2.md
  - Unit 3: unit3.md
  - Terminal: test.md
extra_css:
  - https://cdn.jsdelivr.net/npm/xterm@5.3.0/css/xterm.css
  - css/custom-terminal.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/xterm@5.3.0/lib/xterm.min.js
  - js/terminal-init.js
theme:
  name: simple-blog
  custom_dir: overrides
  favicon: img/logo.png
  logo: img/logo.png
  analytics:
    gtag: G-DRPQMPQQS6
    anonymize_ip: true
  highlightjs: true
  hljs_languages:
    - python
    - yaml
    - C
    - bash
  color_mode: dark
  user_color_mode_toggle: true

